language: ruby
rvm:
  - 2.2
sudo: false
before_install:
  - gem install bundler -v '~> 1.10'
script:
  - bundle exec rake spec
deploy:
  provider: rubygems
  api_key:
    secure:  "qDh1BOlLLokI/gU/5HkAmbsAEE5A384IketR+BB4Pal8BsGGnxnbbSUU79pEU94wCHhUFYDnzq7DbkxbvuBYl2R1y98iq7SkLvLD2XWr6zAYwWM3oQOrv3NTWi3hc93Mz8YxVJ6GFzyKBFf4SmYjf18OkpOHuxKSAF95T6LcSKaVljM3Vy49FOE6DsStcgHs4U7kgjQMFiaN4WI8ul7XrmsC9zLrmMG7EH6ktTcpE0TuLrpmtq4Y1dmDGLA55yEDfnYZVz/TgDpkcCAMNGC92P/3EgW6nsYAb3LJ/LD5qbbMdnMUVwKx9lOyiYkTKM9QtPoEhAxtn5I0DiWgQ+UI1MQAmdiqYScjhle8DpaRhYCSz+WDQc3MDHPEZQsKksA92Cs26Np6JRLDkpAYw2MKjLMnqFe1mDxr9UpnEJbxZJtsV+N6zgEwDMh/rwJXVdns4wIDveOT5rFP9VCfsJxn25In+DNhmeiBhLYMTeUfOPP9+SrH2xLiVnHk0OPy/IDrYTEd0BkGAPQQDQ45MCT0TOoF/bpTFQ8NREOXndTP9RyHS442eIHiQ5+kv4P/kwhBEjebhzIT4W5LYsYOBv2ZInTP2xKoHXveyVaIwMyKc0VwNluCi/xVnc/NpVhiRxgr57drW6z/Piy2uxs26VVfcve+9+EoO+qP2fBhtQ5YOWA="
  on:
    tags: true
addons:
    code_climate:
        repo_token: 
          secure: "AKrgx5PtDa5/pek0hLgtk55SEE4DzCBM1li4eVCPK4CWfo7WgiODN51rnE7uhnABdaeI82t/YuJIyLE37PnsU4dqkXVBXtPmijBkbZy1SZ/bmTsSnOFoMTVWkaCb/iAcr+i5yqJ16bSGLV/t3K80ksyH80WgZTdzmh75pEDKaOBDLI42mgBf/eXkLZ68iuotatLnuLFwVa4mGW79yiJYBxHNstYHEBd0B4Ahutz3BMGFUiwCBx0wer+nVf+RxN+RKkiXRLnOeucwVEcbOOHbm1nkLDhL8U1KQ8lnWNV+RSUPNoOJNoMcgMRKMavDj6TC29e2pO44PWNgICCkUqbvc9Otrac5HG566ZsYZ0gp9BhQxEIpeYkzEUh7a/znLGiQYylrohIf9gsWz3KLGOPD68y4DZfmKgQDZG8ag1ErKmIv1Cna1PmsFA/lXUrZ60hIzgc0Vdw2jb7Ww2GHK35h8kSOCuDOOgmDpLhESvPVb7PPL2ftTLwSH6FT/P7wyfoeSqgotZTKZCw6JZAnV+HjwWB1uzR7dlt/H0qjduCVekWcK7Pq4lnlNI8S4tcAYiJSaL6EcCvrQ2qUAlw2xXYar0ouRgOQgM4H3HCleqkNIZwHxc3GYgdyhhPYqBr8Uq1ziT7NnQ4X94cCu9tuAcvKoqvQiJOKc4HUGCzgPnJiqL8="
